
SRC_DIR  = src
BIN_DIR  = bin
BIN_NAME = empty
BIN_EXT  = .exe

INCLUDES = -I./src -I./include
LIBS = -L./lib -lps4000

CXX = g++

RM = del

all :
	$(CXX) $(SRC_DIR)/empty.cpp $(SRC_DIR)/picoscope.cpp $(INCLUDES) $(LIBS) -o $(BIN_DIR)/$(BIN_NAME)$(BIN_EXT)

clean :
	$(RM) $(BIN_DIR)\$(BIN_NAME)$(BIN_EXT)
